{% set name = "OceanColor" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/OceanColor-{{ version }}.tar.gz
  sha256: 79d58f1ce2b1c9d7b6b49aff15e9753d5afcdb912e60ed6ffd7947be38ff8cbf

build:
  number: 1
  noarch: python
  entry_points:
    - OceanColor=OceanColor.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - aiohttp >=3.8.1
    - click >=8.0
    - fsspec >=2022.1
    - netcdf4 >=1.5.6
    - numpy >=1.21
    - pandas >=1.3
    - pyproj >=3.0
    - python >={{ python_min }}
    - requests >=2.27
    - xarray >=0.19

test:
  imports:
    - OceanColor
  commands:
    - pip check
    - OceanColor --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/castelao/OceanColor
  summary: Deal with NASA Ocean Color data (search and download)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - castelao
